language: python
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7-dev'

matrix:
    allow_failures:
        - python: 3.8-dev

before_install:
    - pip install codecov

install:
    - pip install -r requirements-dev.txt

script:
    - coverage run --source radish -m pytest tests/unit/
    - coverage run -a --source radish -m pytest tests/functional/
    - coverage run -a --source radish -m pytest tests/integration/
    - pip install --editable .
    - bash ./tests/exploratory.sh
    - coverage combine -a
    - coverage report -m

after_success:
    - codecov
