# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Linux'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Linting:
        python.version: '3.7'
        tox.env: lint
      Python35:
        python.version: '3.5'
        tox.env: py35
      Python36:
        python.version: '3.6'
        tox.env: py36
      Python37:
        python.version: '3.7'
        tox.env: py37
      #Python38:
        #python.version: '3.8'
        #tox.env: py38
      Docs:
        python.version: '3.7'
        tox.env: docs
    maxParallel: 4

  steps:
    - template: .azure/steps.yml

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
        tox.env: py35
      Python36:
        python.version: '3.6'
        tox.env: py36
      Python37:
        python.version: '3.7'
        tox.env: py37
      #Python38:
        #python.version: '3.8'
        #tox.env: py38
    maxParallel: 4

  steps:
    - template: .azure/steps.yml
